//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace console_pr3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class search
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public search()
        {
            this.crime = new HashSet<crime>();
        }
    
        public int ID_search { get; set; }
        public int ID_type { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Last_name { get; set; }
        public string Birthday { get; set; }
        public string Adress { get; set; }
        public System.DateTime Last_seen { get; set; }
        public string Contact_number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crime> crime { get; set; }
        public virtual type_of_search type_of_search { get; set; }
    }
}
