//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace console_pr3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int ID_user { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Last_name { get; set; }
        public string Telephone_number { get; set; }
        public string Email { get; set; }
        public int ID_register { get; set; }
    
        public virtual officer officer { get; set; }
        public virtual register register { get; set; }
    }
}
