//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace console_pr3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vacancy
    {
        public int ID_vacancy { get; set; }
        public string Description { get; set; }
        public string Payment { get; set; }
        public int ID_department { get; set; }
    
        public virtual department department { get; set; }
    }
}
