//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crime
    {
        public int ID_crime { get; set; }
        public string Description { get; set; }
        public System.DateTime Date_and_time { get; set; }
        public int ID_article { get; set; }
        public string Suspect { get; set; }
        public string Victims { get; set; }
        public string Adress { get; set; }
        public int ID_department { get; set; }
        public Nullable<int> ID_search { get; set; }
    
        public virtual article article { get; set; }
        public virtual department department { get; set; }
        public virtual search search { get; set; }
    }
}
