//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class officer
    {
        public int ID_officer { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Last_Name { get; set; }
        public string Service_exp { get; set; }
        public System.DateTime Birthday { get; set; }
        public int ID_department { get; set; }
        public int ID_rank { get; set; }
        public Nullable<int> ID_award { get; set; }
        public string Telephone_number { get; set; }
        public string Email { get; set; }
    
        public virtual award award { get; set; }
        public virtual department department { get; set; }
        public virtual rank rank { get; set; }
        public virtual user user { get; set; }
    }
}
